stages:
- name: compile
  steps:
  - runScriptConfig:
      image: node:13.6.0
      shellScript: |-
        cd server
        npm install
        npm run build
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./server/Dockerfile
      buildContext: .
      tag: threes/server
timeout: 60
notification: {}
