version: "3"
services:
  client:
    image: node:11.15.0
    volumes:
      - .:/app
    working_dir: /app/client-ts
    ports:
      - 80:8080 # LAN Support
      # - 127.3.3.3:80:8080
    command: npm start
  server:
    image: node:11.15.0
    environment:
      - MONGO_URL=mongodb://mongo/threeswithfriends
      - JWT_SECRET=changeme
      - LOG_LEVEL=debug
      - NODE_ENV=local
    ports:
      - 4280:4280 # LAN Support
      # - 127.3.3.4:80:4280
    working_dir: /app/server
    volumes:
      - .:/app
    command: npm start
  mongo:
    image: mongo:4.0.9
    volumes:
      - ./db:/data/db
    logging:
      driver: syslog
