// Generated by https://quicktype.io

export interface IPlayer {
  socket:   string;
  isInGame: boolean;
  isReady:  boolean;
  email:    string;
  username: string;
  role:     string;
  _id:      string;
  user:     IUser;
}

export interface IUser {
  _id:        string;
  uuid:       string;
  username:   string;
  email:      string;
  role:       string;
  avatarUrl:  null;
  avatarIcon: string;
  color:      string;
}
