# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:13.6.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - node-modules-

      - run:
          command: |
            cd client-ts
            npm install
            cd ../server
            npm install


      - save_cache:
          paths:
            - client-ts/node_modules
            - server/node_modules
          key: node-modules-{{ checksum "package.json" }}

      #  Build

      - run:
          command: |
            cd client-ts
            npm run build:staging
      - run:
          command: |
            cd server
            npm run build
      