// SERVER EVENTS
export const GAME_OVER_COUNTDOWN = 'GAME_OVER_COUNTDOWN';

export const SET_REMOTE_PLAYER_INFO = 'SET_REMOTE_PLAYER_INFO';
export const CLEAR_REMOTE_PLAYER_INFO = 'CLEAR_REMOTE_PLAYER_INFO';

// SINGLEPLAYER EVENTS
export const SINGLE_GAME_START = 'SINGLE_GAME_START';
export const SINGLE_MOVE = 'SINGLE_MOVE';
export const SINGLE_GAME_OVER = 'SINGLE_GAME_OVER';
export const SINGLE_GAME_PAUSE = 'SINGLE_GAME_PAUSE';

// LOCAL EVENTS
export const GAME_START = 'GAME_START';
export const MOVE = 'MOVE';
export const GAME_OVER = 'GAME_OVER';
export const GAME_PAUSE = 'GAME_PAUSE';

// REMOTE EVENTS
export const REMOTE_GAME_START = 'REMOTE_GAME_START';
export const REMOTE_MOVE = 'REMOTE_MOVE';
export const REMOTE_GAME_OVER = 'REMOTE_GAME_OVER';
export const REMOTE_GAME_PAUSE = 'REMOTE_GAME_PAUSE';