export const SET_REMOTE_PLAYER_INFO = 'SET_REMOTE_PLAYER_INFO';
export const CLEAR_REMOTE_PLAYER_INFO = 'CLEAR_REMOTE_PLAYER_INFO';

export const START_GAME = 'START_GAME';
export const APPLY_REMOTE_STATE = 'APPLY_REMOTE_STATE';

export const GAME_OVER = 'GAME_OVER';
export const NEXT_NUMBER = 'NEXT_NUMBER';

export const REMOTE_NEXT_NUMBER = 'REMOTE_NEXT_NUMBER';
export const REMOTE_GAME_OVER = 'REMOTE_GAME_OVER';
export const REMOTE_GAME_PAUSE = 'REMOTE_GAME_PAUSE';

export const REMOTE_MOVE_UP = 'REMOTE_MOVE_UP';
export const REMOTE_MOVE_DOWN = 'REMOTE_MOVE_DOWN';
export const REMOTE_MOVE_LEFT = 'REMOTE_MOVE_LEFT';
export const REMOTE_MOVE_RIGHT = 'REMOTE_MOVE_RIGHT';