// SERVER EVENTS
export const GAME_OVER_COUNTDOWN = 'GAME_OVER_COUNTDOWN';

export const SET_REMOTE_PLAYER_INFO = 'SET_REMOTE_PLAYER_INFO';
export const CLEAR_REMOTE_PLAYER_INFO = 'CLEAR_REMOTE_PLAYER_INFO';

// SINGLEPLAYER EVENTS
export const SINGLE_GAME_START = 'SINGLE_GAME_START';
export const SINGLE_MOVE = 'SINGLE_MOVE';
export const SINGLE_GAME_OVER = 'SINGLE_GAME_OVER';
export const SINGLE_GAME_PAUSE = 'SINGLE_GAME_PAUSE';

// LOCAL EVENTS
export const GAME_START = 'GAME_START';
export const MOVE = 'MOVE';
export const GAME_OVER = 'GAME_OVER';
export const GAME_PAUSE = 'GAME_PAUSE';

// REMOTE EVENTS
export const REMOTE_GAME_START = 'REMOTE_GAME_START';
export const REMOTE_MOVE = 'REMOTE_MOVE';
export const REMOTE_GAME_OVER = 'REMOTE_GAME_OVER';
export const REMOTE_GAME_PAUSE = 'REMOTE_GAME_PAUSE';

// LOCAL MULTIPLAYER EVENTS
export const LEFT_GAME_START = 'LEFT_GAME_START';
export const LEFT_MOVE = 'LEFT_MOVE';
export const LEFT_GAME_OVER = 'LEFT_GAME_OVER';
export const LEFT_GAME_PAUSE = 'LEFT_GAME_PAUSE';

export const RIGHT_GAME_START = 'RIGHT_GAME_START';
export const RIGHT_MOVE = 'RIGHT_MOVE';
export const RIGHT_GAME_OVER = 'RIGHT_GAME_OVER';
export const RIGHT_GAME_PAUSE = 'RIGHT_GAME_PAUSE';

export const HOST_GAME = 'HOST_GAME';
export const HOST_GAME_SUCCESS = 'HOST_GAME_SUCCESS';
export const HOST_GAME_FAILURE = 'HOST_GAME_FAILURE';

export const JOIN_GAME = 'JOIN_GAME';
export const JOIN_GAME_SUCCESS = 'JOIN_GAME_SUCCESS';
export const JOIN_GAME_FAILURE = 'JOIN_GAME_FAILURE';